import { Router, type IRouter } from "express";
import healthRouter from "./health";
import profileRouter from "./profile";
import forecastRouter from "./forecast";
import activationsRouter from "./activations";
import systemsRouter from "./systems";
import qimenRouter from "./qimen";
import baziHoursRouter from "./baziHours";
import contactsRouter from "./contacts";
import dreamsRouter from "./dreams";
import tasksRouter from "./tasks";
import travelRouter from "./travel";
import chatRouter from "./chat";
import journalRouter from "./journal";
import astrologyRouter from "./astrology";
import notepadRouter from "./notepad";
import adminOntologyRouter from "./adminOntology";
import ontologyExportRouter from "./ontologyExport";
import adminCinderellaRouter from "./adminCinderella";
import adminSynastryRouter from "./adminSynastry";
import adminLunarRouter from "./adminLunar";
import adminForecastTemplatesRouter from "./adminForecastTemplates";
import adminLongTermForecastsRouter from "./adminLongTermForecasts";
import psychologyRouter from "./psychology";
import adminPsychologyRouter from "./adminPsychology";

const router: IRouter = Router();

router.use(healthRouter);
router.use(profileRouter);
router.use(forecastRouter);
router.use(activationsRouter);
router.use(systemsRouter);
router.use(qimenRouter);
router.use(baziHoursRouter);
router.use(contactsRouter);
router.use(dreamsRouter);
router.use(tasksRouter);
router.use(travelRouter);
router.use(chatRouter);
router.use(journalRouter);
router.use(psychologyRouter);
router.use(astrologyRouter);
router.use(notepadRouter);
router.use(adminOntologyRouter);
router.use(ontologyExportRouter);
router.use(adminCinderellaRouter);
router.use(adminSynastryRouter);
router.use(adminLunarRouter);
router.use(adminForecastTemplatesRouter);
router.use(adminLongTermForecastsRouter);
router.use(adminPsychologyRouter);

export default router;
