import { shadcn } from "@clerk/themes";

export const userProfileAppearance = {
  theme: shadcn,
  cssLayerName: "clerk",
  variables: {
    colorPrimary: "hsl(222 90% 63%)",
    colorForeground: "hsl(45 30% 90%)",
    colorMutedForeground: "hsl(164 15% 65%)",
    colorDanger: "hsl(0 70% 62%)",
    colorBackground: "hsl(164 46% 14%)",
    colorInput: "hsl(164 30% 22%)",
    colorInputForeground: "hsl(45 30% 90%)",
    colorNeutral: "hsl(164 25% 35%)",
    fontFamily: "'Inter', sans-serif",
    borderRadius: "0.5rem",
  },
  elements: {
    rootBox: "w-full",
    modalContent: "w-full max-w-[920px]",
    cardBox:
      "rounded-2xl w-[880px] max-w-[95vw] bg-popover border border-border shadow-2xl overflow-hidden",
    card: "!bg-transparent",
    navbar: "bg-transparent border-r border-border",
    navbarButton: "text-foreground",
    navbarButtonIcon: "text-muted-foreground",
    scrollBox: "bg-transparent",
    headerTitle: "text-foreground font-serif text-2xl",
    headerSubtitle: "text-muted-foreground",
    profileSectionTitleText: "text-foreground",
    profileSectionContent: "text-foreground",
    profileSectionPrimaryButton: "text-primary hover:text-primary/90",
    accordionTriggerButton: "text-foreground",
    menuButton: "text-foreground",
    formButtonPrimary: "bg-primary text-primary-foreground hover:bg-primary/90",
    formButtonReset: "text-muted-foreground hover:text-foreground",
    formFieldLabel: "text-foreground",
    formFieldInput: "bg-input border-border text-foreground",
    formFieldHintText: "text-muted-foreground",
    formFieldInfoText: "text-muted-foreground",
    fileDropAreaHint: "text-muted-foreground",
    fileDropAreaButtonPrimary: "text-primary hover:text-primary/90",
    breadcrumbsItem: "text-muted-foreground",
    breadcrumbsItemDivider: "text-muted-foreground",
    breadcrumbsItemCurrent: "text-foreground",
    badge: "text-foreground",
    avatarImageActionsUpload: "text-primary hover:text-primary/90",
    avatarImageActionsRemove: "text-destructive hover:text-destructive/90",
  },
};
